export const DEFAULT_THEME_NAME = 'default-dark'

const darkPalette = {
  '--base-white': '#ffffff',
  '--base-white-rgb': '255, 255, 255',
  '--base-black': '#04050a',
  '--base-black-rgb': '4, 5, 10',
  '--color-bg-app': '#090b11',
  '--color-bg-app-rgb': '9, 11, 17',
  '--color-bg-surface': '#11141c',
  '--color-bg-surface-rgb': '17, 20, 28',
  '--color-bg-elevated': '#171a23',
  '--color-bg-elevated-rgb': '23, 26, 35',
  '--color-border-subtle': '#222631',
  '--color-border-subtle-rgb': '34, 38, 49',
  '--color-border-strong': '#2d313d',
  '--color-border-strong-rgb': '45, 49, 61',
  '--color-text-primary': '#eef0f6',
  '--color-text-primary-rgb': '238, 240, 246',
  '--color-text-secondary': '#c4c7d2',
  '--color-text-secondary-rgb': '196, 199, 210',
  '--color-text-muted': '#8e92a0',
  '--color-text-muted-rgb': '142, 146, 160',
  '--color-text-inverse': '#090b11',
  '--color-text-inverse-rgb': '9, 11, 17',
  '--color-accent': '#2f6dfd',
  '--color-accent-rgb': '47, 109, 253',
  '--color-accent-soft': '#6fa2ff',
  '--color-accent-soft-rgb': '111, 162, 255',
  '--color-accent-strong': '#1f4fc6',
  '--color-accent-strong-rgb': '31, 79, 198',
  '--color-success': '#2ebd94',
  '--color-success-rgb': '46, 189, 148',
  '--color-warning': '#e3b04a',
  '--color-warning-rgb': '227, 176, 74',
  '--color-danger': '#e85a5a',
  '--color-danger-rgb': '232, 90, 90',
  '--color-shadow-soft': '0 12px 32px rgba(0, 0, 0, 0.54)',
  '--color-shadow-strong': '0 20px 65px rgba(0, 0, 0, 0.72)',
  '--color-focus-ring': '#2f6dfd',
  '--color-focus-ring-rgb': '47, 109, 253',
  '--color-grid-line': 'rgba(255, 255, 255, 0.055)',
  '--color-node-red': '#e85a5a',
  '--color-node-red-rgb': '232, 90, 90',
  '--color-node-blue': '#5a8cff',
  '--color-node-blue-rgb': '90, 140, 255',
  '--color-node-highlight': 'rgba(var(--color-accent-rgb), 0.14)',
  '--color-selection-strong': '#2f6dfd',
  '--color-selection-soft': 'rgba(47, 109, 253, 0.18)',
  '--color-surface-muted': '#20232b',
  '--color-panel': '#0d0f15',
  '--color-panel-rgb': '13, 15, 21',
  '--color-input': '#14171f',
  '--color-input-rgb': '20, 23, 31',
  '--color-disabled-bg': '#2a2d33',
  '--color-disabled-text': '#7a7f8a',
  '--color-outline-strong': '#2d313d',
  '--color-outline-contrast': '#171a21',
  '--color-outline-contrast-rgb': '23, 26, 33',
  '--color-detail-stroke': '#2c3646',
  '--color-body-fill-rgb': '150, 165, 185',
  '--color-body-stroke-rgb': '60, 70, 85',
  '--color-detail-fill-rgb': '70, 80, 95',
  '--color-detail-gradient-rgb': '140, 150, 165',
  '--lm-bg-0': 'var(--color-bg-app)',
  '--lm-bg-1': 'var(--color-bg-surface)',
  '--lm-bg-2': 'var(--color-bg-elevated)',
  '--lm-border': 'var(--color-border-subtle)',
  '--lm-text-0': 'var(--color-text-primary)',
  '--lm-text-1': 'var(--color-text-muted)',
  '--lm-grid-line': 'var(--color-grid-line)',
  '--sr-white': 'var(--base-white)',
  '--sr-white-rgb': 'var(--base-white-rgb)',
  '--sr-black': 'var(--base-black)',
  '--sr-black-rgb': 'var(--base-black-rgb)',
  '--sr-primary': 'var(--color-accent)',
  '--sr-accent-danger': 'var(--color-danger)',
  '--sr-surface-muted': 'var(--color-surface-muted)',
  '--sr-text-muted': 'var(--color-text-muted)',
  '--sr-text-strong': 'var(--color-text-primary)',
  '--sr-node-red': 'var(--color-node-red)',
  '--sr-node-blue': 'var(--color-node-blue)',
  '--sr-outline-strong': 'var(--color-border-strong)',
  '--sr-outline-contrast': 'var(--color-outline-contrast)',
}

const lightOverrides = {
  '--color-bg-app': '#f2f4f8',
  '--color-bg-app-rgb': '242, 244, 248',
  '--color-bg-surface': '#e9ecf2',
  '--color-bg-surface-rgb': '233, 236, 242',
  '--color-bg-elevated': '#dde2eb',
  '--color-bg-elevated-rgb': '221, 226, 235',
  '--color-danger-rgb': '187, 74, 74',
  '--color-node-blue-rgb': '90, 140, 255',
  '--color-node-red-rgb': '232, 90, 90',
  '--color-border-subtle': '#c9ced6',
  '--color-border-subtle-rgb': '201, 206, 214',
  '--color-border-strong': '#b1b7c3',
  '--color-border-strong-rgb': '177, 183, 195',
  '--color-text-primary': '#1b1c21',
  '--color-text-primary-rgb': '27, 28, 33',
  '--color-text-secondary': '#31323b',
  '--color-text-secondary-rgb': '49, 50, 59',
  '--color-text-muted': '#575a66',
  '--color-text-muted-rgb': '87, 90, 102',
  '--color-text-inverse': '#ffffff',
  '--color-text-inverse-rgb': '255, 255, 255',
  '--color-success': '#1f8768',
  '--color-success-rgb': '31, 135, 104',
  '--color-warning': '#b57a1e',
  '--color-warning-rgb': '181, 122, 30',
  '--color-danger': '#bb4a4a',
  '--color-shadow-soft': '0 10px 28px rgba(0, 0, 0, 0.12)',
  '--color-shadow-strong': '0 18px 44px rgba(0, 0, 0, 0.18)',
  '--color-grid-line': 'rgba(0, 0, 0, 0.07)',
  '--color-node-blue': '#5a8cff',
  '--color-node-red': 'rgba(47, 109, 253, 0.12)',
  '--color-node-highlight': '#e85a5a',
  '--color-selection-strong': '#2f6dfd',
  '--color-selection-soft': 'rgba(47, 109, 253, 0.16)',
  '--color-surface-muted': '#e1e7ef',
  '--color-panel': '#ffffff',
  '--color-panel-rgb': '255, 255, 255',
  '--color-input': '#fafbff',
  '--color-input-rgb': '250, 251, 255',
  '--color-disabled-bg': '#e3e7ee',
  '--color-disabled-text': '#97a1b4',
  '--color-outline-strong': '#3c4961',
  '--color-detail-stroke': '#354156',
}

const lightPalette = {
  ...darkPalette,
  ...lightOverrides,
  '--lm-bg-0': 'var(--color-bg-app)',
  '--lm-bg-1': 'var(--color-bg-surface)',
  '--lm-bg-2': 'var(--color-bg-elevated)',
  '--lm-border': 'var(--color-border-subtle)',
  '--lm-text-0': 'var(--color-text-primary)',
  '--lm-text-1': 'var(--color-text-muted)',
  '--lm-grid-line': 'var(--color-grid-line)',
  '--sr-outline-strong': 'var(--color-border-strong)',
  '--sr-outline-contrast': 'var(--color-outline-contrast)',
}

export const DEFAULT_THEMES = [
  {
    id: 'default-dark',
    name: 'default-dark',
    required_plan: 'free',
    css_vars: darkPalette,
  },
  {
    id: 'default-light',
    name: 'default-light',
    required_plan: 'free',
    css_vars: lightPalette,
  },
]
